### ISSUE TITLE
In the README, it could be made clearer that two processes are involved to instantiate the app.

### ISSUE THREAD

**Issue by paul-hammant** [protubero/angular-jooby-starter#3]
For example, "To start the client, execute npm start at the .." would be better as "To start the client, **in a second terminal** execute npm start at the .."

Also (and I am not sure about this), there's the following section: "Build distribution".  It implies that the server and BFF pieces are pulled together into a single zip, and would make a better (simpler?) server deployment - Jooby being a fine server of static content (even if not web scale). What's not said is whether the `mvn package` suggested would recurse into the client folder to build the `npm` pieces.  Or whether it requires you to have done steps 1-7 before you try `mvn package`. If it does (and I'm pointlessly discussing it now), it hints that there is also a `jooby:run` that SHOULD run at this level that also recurses into client/ for the npm pieces.  Also it is worth reminding folks that `mvn install` also an alternate to `mvn package` making the recommendation "..execute mvn package or mvn install in the root.."

Great work by the way.

**Comment by protubero** [comment]
Hi Paul,

thank you very much, that was very very helpful feedback. I've already
changed some text but still not finished.

kind regards,
Manfred

2017-08-13 17:34 GMT+02:00 Paul Hammant <notifications@github.com>:

**Comment by protubero** [comment]
I tried to improve the whole text. I still havte to make some assumptions about existing knowledge of the reader. Will not work well without some basic knowledge about maven and node/npm/angular.
